import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("verify-pilot", "routes/verify-pilot.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("verify-otp", "routes/verify-otp.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("verify-password-reset", "routes/verify-password-reset.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("generate-card", "routes/generate-card.tsx"),
  route("my-requests", "routes/my-requests.tsx"),
  route("insurance", "routes/insurance.tsx"),
  route("tests", "routes/tests.tsx"),
  route("tests/:level", "routes/tests.$level.tsx"),
  route("tests/results", "routes/tests.results.tsx"),
  route("apply-membership", "routes/apply-membership.tsx"),
  route("renew-membership", "routes/renew-membership.tsx"),
  route("upgrade-rating", "routes/upgrade-rating.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("upload-profile-image", "routes/upload-profile-image.tsx"),
  route("download-insurance-card/:policyId", "routes/download-insurance-card.$policyId.tsx"),
  route("admin", "routes/admin.tsx"),
  route("manage-users", "routes/manage-users.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/search-pilot", "routes/api.search-pilot.tsx"),
  // Catch-all route for 404s and DevTools requests (must be last)
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
